### ISSUE TITLE
Your API credentials are exposed!!!!

### ISSUE THREAD

**Issue by Zac-Zajdel** [janaiscoding/letterboxd-clone#1]
You need to recreate your API credentials for firebase and NOT publish them to Github!

See here: https://github.com/janaiscoding/letterboxd-clone/blob/main/src/firebase/firebase.js

**Comment by Zac-Zajdel** [comment]
No problem! I came by your Letterboxd clone while looking into potentially creating a competitor to it.

Like what you have here!

Cheers 🥳

**Comment by janaiscoding** [comment]
> No problem! I came by your Letterboxd clone while looking into potentially creating a competitor to it.
> 
> Like what you have here!
> 
> Cheers 🥳

That sounds exciting! I'd like to see what you create if it will be open-source, certainly there is a lot of space out there for movie-lovers social medias 👀 

I made this project just because I love that website and movies, so it was the most fun way to learn at the time! However I'd love to go back through it and apply all the things I learned since the day it was made! 

Best of luck with your project, I hope to be one of the users soon! 🥳
